version: '3'
services:
  db:
    image: postgres:11.1-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 7000:7000
    environment:
      - DB_ENGINE=django.db.backends.postgresql_psycopg2
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
volumes:
  postgresql:
