# Generated by Django 4.2.3 on 2023-08-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todolist_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
